apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-api-config
data:
  ASPNETCORE_ENVIRONMENT: "k8s"
  ConnectionStrings__DefaultConnection: "Host=postgres-service;Port=5432;Username=healthmed;Password=healthmed;Database=healthMedUsersDb;"
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft_AspNetCore: "Warning"
  AllowedHosts: "*"
